<?php
namespace Dma\Dma_elementgenerator\Command;
/**
 * Created By Conversoft Generator
 * https://conversoft.rocks
 * https://github.com/conversoft
 * @author Thomas Lonnemann <thomas@conversoft.rocks>
**/
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Contao\CoreBundle\Framework\FrameworkAwareTrait;
use Contao\CoreBundle\Command\AbstractLockedCommand;



//ini_set("memory_limit", "4G");
class ContaoDmaDma_elementgeneratorBundleCommand extends AbstractLockedCommand
{
    use FrameworkAwareTrait;

    protected $output;

    public function __construct()
    {
        putenv('TMPDIR=' . getcwd() . '/system/tmp/');
        parent::__construct();
    }

    protected function configure()
    {
        $this
            // the name of the command (the part after "vendor/bin/contao-console ")
            ->setName( 'dma:dma_elementgenerator')
            // the short description shown while running "php vendor/bin/contao-console list"
            ->setDescription('Description here')
            // the full command description shown when running the command with
            // the "--help" option
            ->setHelp('This command was generated by conversoft bundle generator');
    }

    protected function executeLocked(InputInterface $input, OutputInterface $output)
    {
        // Get Contao
        $this->framework = $this->getContainer()->get('contao.framework');
        $this->framework->initialize();
        include_once(__DIR__ . '/../Resources/contao/languages/de/default.php');
        // set output to have error and success and input
        $this->output = new SymfonyStyle($input, $output);

    }

    
}
